FCCtest_center:
  Distance: 20
  Galaxy name: FCC1test
  F_corr: 0.99999
  velocity: 1369
  eff_r: 28.6
  FWHM: 3.59
  FWHM_err: 0.04
  beta: 3.97
  beta_err: 0.44
  LSF: 3.06
  LSF_err: 0.03
  centre: [220, 220]
  gal_mask: [1,1,1,1,1]
  star_mask: [[1,1,1]]
  over_lum: []
  impostor_filter: [[],[],[]]
  interloper_filter: []
  emissions:
    OIII_1: [750, null, null]
    OIII_2: [null, Amp_2D_OIII_1/3, 'wave_OIII_1 - 47.9399 * (1+{})']
